# Generated by Django 5.1.5 on 2025-01-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Yet to Apply", "Yet to Apply"),
                            ("Applied", "Applied"),
                            ("Interview Offer", "Interview Offer"),
                            ("Interview Completed", "Interview Completed"),
                            ("Offered", "Offered"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Yet to Apply",
                        max_length=50,
                    ),
                ),
                ("deadline", models.DateField()),
                ("date_applied", models.DateField()),
                ("resume_link", models.URLField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
