# Generated by Django 5.1.5 on 2025-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobapplication_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
